[16.0] [MIG] product_brand
OCA/brand pull request #132
Opened 2022-10-10 08:36 UTC by marielejeune

2022-10-10 08:37 UTC, marielejeune commented
TODO: fix the openupgradelib dependency to benefit from https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade_160.py

2022-10-10 09:38 UTC, sbejaoui approved these changes

2022-10-19 13:47 UTC, lmignon requested changes
@marielejeune When I try to open the product form, an exception occurs:

```
Traceback (most recent call last):
  File "/opt/odoo/odoo/api.py", line 983, in get
    cache_value = field_cache[record._ids[0]]
KeyError: 12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/fields.py", line 1132, in __get__
    value = env.cache.get(record, self)
  File "/opt/odoo/odoo/api.py", line 990, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'product.product(12,).sales_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1534, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1563, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1760, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 138, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 673, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 2991, in read
    return self._read_format(fnames=fields, load=load)
  File "/opt/odoo/odoo/models.py", line 3131, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/opt/odoo/odoo/models.py", line 5841, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/fields.py", line 1181, in __get__
    self.compute_value(recs)
  File "/opt/odoo/odoo/fields.py", line 1340, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/addons/mail/models/mail_thread.py", line 403, in _compute_field_value
    return super()._compute_field_value(field)
  File "/opt/odoo/odoo/models.py", line 4186, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo/addons/sale/models/product_product.py", line 28, in _compute_sales_count
    for group in self.env['sale.report']._read_group(domain, ['product_id', 'product_uom_qty'], ['product_id']):
  File "/opt/odoo/odoo/models.py", line 2176, in _read_group
    return self.read_group(domain, fields, groupby, offset, limit, orderby, lazy)
  File "/opt/odoo/odoo/models.py", line 2216, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/opt/odoo/odoo/models.py", line 2241, in _read_group_raw
    query = self._where_calc(domain)
  File "/opt/odoo/odoo/models.py", line 4386, in _where_calc
    return expression.expression(domain, self).query
  File "/opt/odoo/odoo/osv/expression.py", line 444, in __init__
    self.query = Query(model.env.cr, model._table, model._table_query) if query is None else query
  File "/opt/odoo/addons/sale/report/sale_report.py", line 202, in _table_query
    return self._query()
  File "/mnt/data/odoo-addons-dir/product_brand/reports/sale_report.py", line 17, in _query
    return super()._query(with_clause, fields, groupby, from_clause)
TypeError: SaleReport._query() takes 1 positional argument but 5 were given
```

2022-10-19 14:08 UTC, lmignon commented
@marielejeune I took the liberty to fix the remaining error to move forward with this PR....

2022-10-19 14:08 UTC, lmignon commented
/ocabot migration product_brand

2022-10-19 14:11 UTC, pedrobaeza commented
/ocabot migration product_brand

2022-10-19 14:34 UTC, lmignon approved these changes
The remaining errors are now fixed.
LGTM (Code review + functional tests)

2022-10-19 14:37 UTC, pedrobaeza commented
/ocabot merge nobump

2022-10-19 14:43 UTC, merged

2022-10-19 14:45 UTC, lmignon commented
thank you @pedrobaeza for the merge!

2022-10-19 14:46 UTC, pedrobaeza commented
You're welcome :smiley: