[MIG][14.0] product brand purchase report
OCA/brand pull request #158
Opened 2023-02-01 13:24 UTC by ilyasProgrammer

Migrated product brand purchase report
Renamed to product brand purchase 
Added brand menu under purchase config.

2023-02-01 13:52 UTC, francesco-ooops approved these changes
Functional review ok! 

This module allows users to manage brands in purchase app.

2023-02-02 12:55 UTC, geomer198 approved these changes
Code Review ok!

2023-02-02 13:16 UTC, francesco-ooops commented
@max3903 @sbejaoui could this work?

2023-02-09 09:03 UTC, francesco-ooops requested changes
@ilyasProgrammer

2023-02-09 09:03 UTC, francesco-ooops commented on product_brand_purchase/readme/USAGE.rst
> +#. You can now group by brand.
#. "Product brands" menu is now accessible also under *Purchase > Configuration > Products*

2023-02-09 09:03 UTC, francesco-ooops commented on product_brand_purchase/views/product_brand_view.xml
> +        id="menu_product_in_config_purchase_product_brand"
name="Product Brands"

2023-02-09 15:00 UTC, ilyasProgrammer commented
@francesco-ooops updated

2023-02-09 15:06 UTC, francesco-ooops commented
@OCA/brand-maintainers is this good for merge?

2023-02-16 09:00 UTC, francesco-ooops commented
@sbejaoui if you have a moment to check this, thanks!

2023-02-16 09:10 UTC, sbejaoui approved these changes
LGTM, code review

2023-02-16 09:10 UTC, sbejaoui commented
/ocabot merge nobump

2023-02-16 09:19 UTC, merged