13.0 mig product pricelist brand
OCA/brand pull request #33
Opened 2020-05-30 07:55 UTC by feketemihai

2020-11-04 16:39 UTC, qgroulard requested changes
Well, I don't know how but I didn't see this PR and opened https://github.com/OCA/brand/pull/44.
I guess we can get the better of both PRs so please have a look at https://github.com/OCA/brand/pull/44.

First, please follow the migration guidelines (https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto) in order to keep the history and solve formatting issues.
I can't find any trace of this module (here nor in repo product-attribute).

Here are my comments, I'm looking forward to reading your suggestions.

2020-11-04 16:39 UTC, qgroulard commented on product_pricelist_brand/models/product_pricelist.py
> +    def _compute_price_rule(self, products_qty_partner, date=False,
This looks like a lot of duplicated code to me.
The base code is definitely not meant to be extended. In my version I override `_compute_price_rule_get_items`, I don't really like it neither but still I think it is a bit cleaner.
Unless there is a good reason to  work on `_compute_price_rule` that I am missing ?

2020-11-04 16:39 UTC, qgroulard commented on product_pricelist_brand/models/product_pricelist.py
> +    def _onchange_applied_on(self):
In the base module there is no `_onchange_applied_on` but updates in create and write, it is more robust to stick to that.
Plus don't forget the method `_check_product_consistency`.

2021-06-02 12:56 UTC, sbejaoui commented
@feketemihai , any news about this PR?

2021-11-28 12:27 UTC, closed without merging