[FIX] account_brand: unable to pay invoice if brand is required
OCA/brand pull request #66
Opened 2021-05-16 09:56 UTC by cubells

If brand is required I can't pay the invoice. A "Brand is required" message is raised.

2021-05-17 07:53 UTC, sbejaoui commented
Hi @cubells ,

Thank you for this PR.

I believe the fix should be here https://github.com/OCA/brand/blob/13.0/account_brand/models/account_move.py#L23.

The check for brand required must be done only for out_invoice and out_refund

2021-05-17 08:01 UTC, cubells commented
Hi @sbejaoui :+1: 
No. I have an `out_invoice` and I get that error. In my case, brand_id is required so an error is raised.

2021-05-17 08:12 UTC, sbejaoui commented
> Hi @sbejaoui :
> No. I have an `out_invoice` and I get that error. In my case, brand_id is required so an error is raised.

The payment move type is 'entry'. So if you exclude it from the check it will work

try this change here https://github.com/OCA/brand/blob/13.0/account_brand/models/account_move.py#L23

```python
    def _is_brand_required(self):
        self.ensure_one()
        if self.type in ("out_invoice", "out_refund"):
            return super()._is_brand_required()
        return False 
 ```

2021-05-17 08:20 UTC, cubells commented
@sbejaoui Sure it works.

But then, why we need `_is_brand_required` method? Return always `False` and it works. If I put 'in_invoice', 'in_refund', 'out_invoice' and 'out_refund', I put all the options.

Invoices are `entries` in version 13.0 too.

2021-05-17 08:47 UTC, sbejaoui commented
> @sbejaoui Sure it works.
> 
> But then, why we need `_is_brand_required` method? Return always `False` and it works. If I put 'in_invoice', 'in_refund', 'out_invoice' and 'out_refund', I put all the options.
> 
> Invoices are `entries` in version 13.0 too.

it returns False for all move type's except customer invoice for which it check with the company configuration.
https://github.com/OCA/brand/blob/13.0/brand/models/res_brand_mixin.py#L34

In v12 we excluded vendor bills as we had the check only in account.invoice model. now since this check was moved to account.move we should exclude other type of entries.

2021-05-18 05:41 UTC, cubells commented
@sbejaoui 
Then, I think the solution is this:

https://github.com/OCA/brand/pull/66/files#diff-ea44e361057f5edbc4ccf7beb2bbfd53c094178e51c365503f27f9abef354b06R23

2021-05-18 06:42 UTC, cubells commented
I see that test are failing. I push a new solution later.

2021-05-18 07:01 UTC, sbejaoui requested changes

2021-05-18 07:01 UTC, sbejaoui commented on account_brand/models/account_move.py
>          return super()._is_brand_required()
Let be exclusive to prevent the same issue on other types
```suggestion
        if self.type in ("out_invoice", "out_refund"):
            return super()._is_brand_required()
        return False
```

now, we should add the move type in unit tests: https://github.com/OCA/brand/blob/13.0/account_brand/tests/test_brand_mixin.py#L23

2021-06-07 08:49 UTC, sbejaoui approved these changes

2021-06-07 08:50 UTC, sbejaoui commented
can you please check travis

2021-06-14 10:14 UTC, fgarcia-humanoide commented
tested in production

same error

¡Algo salió mal!×
Brand is required

2021-06-14 10:22 UTC, fgarcia-humanoide commented
Is it necessary to define brand y pos?

If you do not define brand in pos , you do not have brand information of all your sales.

2021-06-14 10:34 UTC, fgarcia-humanoide commented
the problem is not paying the invoice, the problem is to close pos session

2022-01-09 12:29 UTC, closed without merging